#!/usr/bin/env node
/**
 * import-books.js — Automated book importer for Livreo
 *
 * Usage:
 *   node import-books.js livres.csv
 *   node import-books.js livres.csv --base-url https://web-production-c5899.up.railway.app
 *   node import-books.js livres.csv --username admin --password secret123
 *
 * Options:
 *   --base-url URL     Server URL (default: http://localhost:3000)
 *   --username USER    Admin username (overrides ADMIN_USERNAME in .env)
 *   --password PASS    Admin password (overrides ADMIN_PASSWORD in .env)
 *
 * Reads a CSV (semicolon-separated), downloads covers from Google Books,
 * compresses them with sharp, then uploads everything to the Livreo API.
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { parse } = require('csv-parse/sync');
const sharp = require('sharp');
const fetch = require('node-fetch');
const FormData = require('form-data');

// ─── CLI argument parser ─────────────────────────────────────────────────────
function getArg(args, flag, fallback) {
  const idx = args.indexOf(flag);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : fallback;
}

// ─── Configuration ───────────────────────────────────────────────────────────
const TEMP_DIR = path.join(__dirname, 'temp');
const DEFAULT_BASE_URL = 'http://localhost:3000';
const DEFAULT_STOCK = 20;
const FEATURED_COUNT = 10; // first N books marked featured
const IMAGE_MAX_WIDTH = 600;
const IMAGE_QUALITY = 75;
const IMAGE_MAX_SIZE = 150 * 1024; // 150 KB

// Placeholder cover (solid grey with text — generated by sharp)
async function generatePlaceholder(title) {
  const safe = escapeXml(title.substring(0, 30));
  const svg = `<svg width="400" height="600" xmlns="http://www.w3.org/2000/svg">
    <rect width="400" height="600" fill="#E0E0E0"/>
    <text x="200" y="280" font-family="Arial" font-size="24" fill="#757575"
          text-anchor="middle" dominant-baseline="middle">Pas de couverture</text>
    <text x="200" y="320" font-family="Arial" font-size="16" fill="#9E9E9E"
          text-anchor="middle" dominant-baseline="middle">${safe}</text>
  </svg>`;
  return sharp(Buffer.from(svg)).jpeg({ quality: IMAGE_QUALITY }).toBuffer();
}

function escapeXml(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

// ─── Cookie-aware fetch wrapper ──────────────────────────────────────────────
class SessionFetch {
  constructor(baseUrl) {
    this.baseUrl = baseUrl.replace(/\/$/, '');
    this.cookies = '';
  }

  async fetch(endpoint, options = {}) {
    const url = endpoint.startsWith('http') ? endpoint : `${this.baseUrl}${endpoint}`;
    const headers = { ...options.headers };
    if (this.cookies) headers['Cookie'] = this.cookies;

    const res = await fetch(url, { ...options, headers });

    // Capture set-cookie headers
    const raw = res.headers.raw();
    const setCookies = raw['set-cookie'];
    if (setCookies) {
      const parsed = setCookies.map(c => c.split(';')[0]);
      const existing = this.cookies ? this.cookies.split('; ').reduce((m, c) => {
        const [k] = c.split('=');
        m[k] = c;
        return m;
      }, {}) : {};
      parsed.forEach(c => {
        const [k] = c.split('=');
        existing[k] = c;
      });
      this.cookies = Object.values(existing).join('; ');
    }

    return res;
  }

  async fetchJSON(endpoint, options = {}) {
    const res = await this.fetch(endpoint, options);
    return res.json();
  }
}

// ─── Google Books cover fetcher ──────────────────────────────────────────────
async function fetchCoverFromGoogle(title, author) {
  const query = encodeURIComponent(`${title} ${author}`);
  const url = `https://www.googleapis.com/books/v1/volumes?q=${query}&maxResults=1`;

  try {
    const res = await fetch(url, { timeout: 10000 });
    if (!res.ok) return null;
    const data = await res.json();

    if (!data.items || data.items.length === 0) return null;

    const imageLinks = data.items[0].volumeInfo?.imageLinks;
    if (!imageLinks) return null;

    // Prefer the largest available thumbnail
    const imageUrl = (imageLinks.thumbnail || imageLinks.smallThumbnail)
      .replace('&edge=curl', '')
      .replace('zoom=1', 'zoom=2'); // request higher resolution

    const imgRes = await fetch(imageUrl, { timeout: 10000 });
    if (!imgRes.ok) return null;

    return Buffer.from(await imgRes.arrayBuffer());
  } catch {
    return null;
  }
}

// ─── Image compression with sharp ───────────────────────────────────────────
async function compressImage(buffer) {
  let result = await sharp(buffer)
    .resize({ width: IMAGE_MAX_WIDTH, withoutEnlargement: true })
    .jpeg({ quality: IMAGE_QUALITY, mozjpeg: true })
    .withMetadata(false) // strip EXIF
    .toBuffer();

  // If still too large, reduce quality progressively
  let quality = IMAGE_QUALITY;
  while (result.length > IMAGE_MAX_SIZE && quality > 30) {
    quality -= 10;
    result = await sharp(buffer)
      .resize({ width: IMAGE_MAX_WIDTH, withoutEnlargement: true })
      .jpeg({ quality, mozjpeg: true })
      .withMetadata(false)
      .toBuffer();
  }

  return result;
}

// ─── Calculate originalPrice = promoPrice × 1.30, rounded up to next 100 ───
function calcOriginalPrice(promoPrice) {
  const raw = promoPrice * 1.30;
  return Math.ceil(raw / 100) * 100;
}

// ─── Parse CSV ───────────────────────────────────────────────────────────────
function parseCSV(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const records = parse(content, {
    delimiter: ';',
    columns: true,
    skip_empty_lines: true,
    trim: true,
    bom: true,
  });

  return records.map(r => ({
    number: parseInt(r['N°'] || r['No'] || '0', 10),
    title: r['Titre'] || '',
    author: r['Auteur'] || '',
    category: r['Catégorie'] || r['Categorie'] || 'Autre',
    price: parseInt((r['Prix suggéré (FCFA)'] || r['Prix suggere (FCFA)'] || '0').replace(/\s/g, ''), 10),
    description: r['Description courte'] || r['Description'] || '',
  }));
}

// ─── Main ────────────────────────────────────────────────────────────────────
async function main() {
  const args = process.argv.slice(2);
  if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
    console.log(`
Usage: node import-books.js <fichier.csv> [options]

Options:
  --base-url URL     Serveur cible (défaut: http://localhost:3000)
  --username USER    Identifiant admin (défaut: ADMIN_USERNAME dans .env)
  --password PASS    Mot de passe admin (défaut: ADMIN_PASSWORD dans .env)
  --help, -h         Afficher cette aide
`);
    process.exit(0);
  }

  const csvFile = args[0];
  const baseUrl = getArg(args, '--base-url', DEFAULT_BASE_URL);
  const adminUsername = getArg(args, '--username', process.env.ADMIN_USERNAME || 'admin');
  const adminPassword = getArg(args, '--password', process.env.ADMIN_PASSWORD || 'livreo2024');

  if (!fs.existsSync(csvFile)) {
    console.error(`❌ Fichier introuvable : ${csvFile}`);
    process.exit(1);
  }

  console.log(`\n📚 Livreo — Import de livres`);
  console.log(`   Fichier  : ${csvFile}`);
  console.log(`   Serveur  : ${baseUrl}`);
  console.log(`   Admin    : ${adminUsername}`);
  console.log('');

  // 1. Parse CSV
  const books = parseCSV(csvFile);
  console.log(`📄 ${books.length} livres trouvés dans le fichier CSV\n`);

  if (books.length === 0) {
    console.error('❌ Aucun livre trouvé dans le fichier');
    process.exit(1);
  }

  // 2. Create temp directory
  if (!fs.existsSync(TEMP_DIR)) fs.mkdirSync(TEMP_DIR, { recursive: true });

  // 3. Login to admin
  const api = new SessionFetch(baseUrl);
  console.log('🔐 Connexion admin...');

  try {
    const loginRes = await api.fetch('/api/admin/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: adminUsername, password: adminPassword }),
    });
    const loginData = await loginRes.json();

    if (!loginData.success) {
      console.error(`❌ Connexion échouée : ${loginData.message}`);
      process.exit(1);
    }
    console.log('✅ Connecté en tant qu\'admin\n');
  } catch (err) {
    console.error(`❌ Impossible de se connecter au serveur : ${err.message}`);
    process.exit(1);
  }

  // 4. Ensure all categories exist
  console.log('🗂️  Vérification des catégories...');
  let existingCategories;
  try {
    const categoriesRes = await api.fetchJSON('/api/categories');
    existingCategories = new Set(
      Array.isArray(categoriesRes) ? categoriesRes.map(c => c.name) : []
    );
  } catch (err) {
    console.error(`❌ Impossible de récupérer les catégories : ${err.message}`);
    existingCategories = new Set();
  }

  const csvCategories = [...new Set(books.map(b => b.category))];
  let categoriesCreated = 0;

  for (const cat of csvCategories) {
    if (!existingCategories.has(cat)) {
      try {
        const catRes = await api.fetch('/api/categories', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ name: cat }),
        });
        if (catRes.status === 201 || catRes.status === 200) {
          existingCategories.add(cat);
          categoriesCreated++;
          console.log(`   ✅ Catégorie créée : ${cat}`);
        } else {
          const err = await catRes.json();
          console.log(`   ⚠️  Catégorie "${cat}" : ${err.message || 'erreur'}`);
        }
      } catch (err) {
        console.log(`   ⚠️  Erreur catégorie "${cat}" : ${err.message}`);
      }
    }
  }

  if (categoriesCreated === 0) {
    console.log('   Toutes les catégories existent déjà');
  }
  console.log('');

  // 5. Import books one by one
  let success = 0;
  let errors = 0;
  const errorList = [];

  for (let i = 0; i < books.length; i++) {
    const book = books[i];
    const num = i + 1;
    const label = `Livre ${num}/${books.length} : ${book.title}`;

    try {
      // 5a. Download or generate cover image
      process.stdout.write(`📖 ${label} — couverture... `);

      let imageBuffer = await fetchCoverFromGoogle(book.title, book.author);

      if (imageBuffer) {
        imageBuffer = await compressImage(imageBuffer);
        process.stdout.write('OK... ');
      } else {
        imageBuffer = await generatePlaceholder(book.title);
        process.stdout.write('placeholder... ');
      }

      // Save to temp for upload
      const imagePath = path.join(TEMP_DIR, `book_${num}.jpg`);
      fs.writeFileSync(imagePath, imageBuffer);

      // 5b. Prepare form data
      const form = new FormData();
      form.append('title', book.title);
      form.append('author', book.author);
      form.append('category', book.category);
      form.append('description', book.description);
      form.append('promoPrice', String(book.price));
      form.append('originalPrice', String(calcOriginalPrice(book.price)));
      form.append('stock', String(DEFAULT_STOCK));
      form.append('featured', num <= FEATURED_COUNT ? 'true' : 'false');
      form.append('image', fs.createReadStream(imagePath), {
        filename: `cover_${num}.jpg`,
        contentType: 'image/jpeg',
      });

      // 5c. Upload to API
      const res = await api.fetch('/api/books', {
        method: 'POST',
        headers: form.getHeaders(),
        body: form,
      });

      if (res.status === 201 || res.status === 200) {
        await res.json(); // consume body
        console.log('✅');
        success++;
      } else {
        const result = await res.json();
        throw new Error(result.message || `HTTP ${res.status}`);
      }
    } catch (err) {
      console.log(`❌ ${err.message}`);
      errors++;
      errorList.push({ num, title: book.title, error: err.message });
    }

    // Small delay to avoid overwhelming the server / Google API
    if (i < books.length - 1) {
      await new Promise(r => setTimeout(r, 500));
    }
  }

  // 6. Cleanup temp directory
  console.log('\n🧹 Nettoyage des fichiers temporaires...');
  try {
    fs.rmSync(TEMP_DIR, { recursive: true, force: true });
    console.log('   Dossier temp/ supprimé');
  } catch {
    console.log('   ⚠️  Impossible de supprimer le dossier temp/');
  }

  // 7. Summary
  console.log('\n' + '='.repeat(50));
  console.log('  RESUME DE L\'IMPORTATION');
  console.log('='.repeat(50));
  console.log(`   Livres importes avec succes : ${success}/${books.length}`);
  console.log(`   Erreurs : ${errors}`);

  if (errorList.length > 0) {
    console.log('\n   Livres en erreur :');
    errorList.forEach(e => {
      console.log(`   - #${e.num} "${e.title}" : ${e.error}`);
    });
  }

  console.log('\n✨ Importation terminée !\n');
}

main().catch(err => {
  console.error(`\n💥 Erreur fatale : ${err.message}`);
  process.exit(1);
});
